# root_id                        = "tf-cafes"
# root_name                      = "Learn Terraform ES"
# default_location               = "centralindia"
# deploy_corp_landing_zones      = false
# deploy_online_landing_zones    = false
# deploy_sap_landing_zones       = false
# deploy_management_resources    = false
# deploy_connectivity_resources  = false
# security_contact_email_address = "kartikesh954@gmail.com"